### ISSUE TITLE
This is a legendary!

### ISSUE THREAD

**Issue by lukebyrne** [alecrubin/pytorch-serverless#1]
Hi Alec,

Thanks for this. 

I am trying to get a version of the Lesson 3 Rossman structured data going in a real world API.

Are you planning on doing serverless versions of this for each type of Neural Network that the Fast.ai course covers?

Kind regards,

Luke

**Comment by alecrubin** [comment]
Thanks Luke! Yes, I am planning on adding one for each type. Was going to do an nlp one next, but I can do a regression one as well. Most likely will create subfolders under the `fastai/` directory with the necessary files for each model type and have corresponding handlers in the `api/` directory. Then you'll just specify the model type in the `serverless.yml` to select which files and folders will be packaged when deploying.

**Comment by mattmcclean** [comment]
Great work Alec! How did you manage to keep the Lambda deployment package under 250MB uncompressed? I was trying to build a similar demo of AWS Lambda with Fast.ai yesterday using the [Chalice](https://github.com/aws/chalice) framework but had issues keeping the python lib dependencies under the limit. Resorted to including numpy and pytorch and had no room for cv2.

**Comment by alecrubin** [comment]
Thanks Matt! The serverless-python-requirements plugin has a `zip` option, which adds an `unzip_requirements.py` to your deployment package, and zips all your requirements into a`.requirements.zip`. After that, your deployment package get zipped, effectively “double zipping” so that when AWS first unzips your deployment package, it evaluates the size of your code plus the zipped requirements, keeping you under the size limit. When the first request comes in, it unzips your requirements. Then the scheduled event defined in the `serverless.yml` keeps the lambda warm.
